---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-webhooks-marqeta-secret
secretDescriptor:
  backendType: secretsManager
  data:
    - key: marqeta-webhook-prod
      name: username
      property: username
    - key: marqeta-webhook-prod
      name: password
      property: password
    - key: marqeta-webhook-prod
      name: secret
      property: secret
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-webhooks-fnbo-secret
secretDescriptor:
  backendType: secretsManager
  data:
    - key: fnbo-webhook-prod
      name: secret
