apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - disruptionbudget.yaml
  - service.yaml
  - service-monitor.yaml

configMapGenerator:
  - name: mino-admin-gateway-env-vars
    literals:
      - SENTRY_DSN=https://ecadb1062a014234ba941b6df1913280@sentry.io/3574953
