apiVersion: v1
kind: Service
metadata:
  name: mino-admin-gateway
  labels:
    app: mino-admin-gateway
spec:
  ports:
    - port: 8443
      name: https
    - port: 8081
      name: http-actuator
  selector:
    app: mino-admin-gateway
  type: ClusterIP
