apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - disruptionbudget.yaml
  - service.yaml
  - service-monitor.yaml

configMapGenerator:
  - name: mino-test-capabilities-env-vars
    literals:
      - SWAGGER_ENABLED=false
      - SENTRY_DSN=https://cb8ac6556abb4a7cbc2a1e6bbe77e866@o257648.ingest.sentry.io/5319614
      - REGISTRATION_KEY_ID=cb914c22-a281-4e1d-bc21-b11e2f05a433
