--- 
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-kyc-marqeta-password
secretDescriptor:
  backendType: secretsManager
  data:
    - key: marqeta-password-prod
      name: password
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-kyc-client-credentials-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - kyc-client-credentials-prod
