---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dex-cluster-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-readonly
subjects:
  - kind: Group
    name: "gen6-ventures:Engineering Team"
  - kind: Group
    name: "gen6-ventures:QA"
  - kind: Group
    name: "gen6-ventures:Front End"
  - kind: Group
    name: "gen6-ventures:Back End"
  - kind: Group
    name: "gen6-ventures:Operations"
  - kind: Group
    name: "gen6-ventures:Security"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    app: dex-k8s-authenticator
    chart: dex-k8s-authenticator-1.2.0
    env: prod
    heritage: Helm
    release: platform
  name: platform-dex-k8s-authenticator
  namespace: dex-k8s-auth
spec:
  rules:
  - host: login.us-east-1.prod.milli-bank.com
    http:
      paths:
      - backend:
          serviceName: platform-dex-k8s-authenticator
          servicePort: 5555
        path: /
  tls:
  - hosts:
    - login.us-east-1.prod.milli-bank.com
    secretName: cert-auth-login
---
apiVersion: v1
data:
  config.yaml: |-
    listen: http://0.0.0.0:5555
    web_path_prefix: /
    debug: false
    clusters:
    - client_id: dex-k8s-authenticator
      client_secret: yPnRbu1MYW2OAFgYF13gkj9QMprhWAjBTKpKTO5mIuc5IE5X 
      description: Milli Production Cluster
      issuer: https://dex.us-east-1.prod.milli-bank.com
      k8s_ca_pem: |-
          -----BEGIN CERTIFICATE-----
          MIIC0zCCAbugAwIBAgIMFi6LBaD6hhhGDUZxMA0GCSqGSIb3DQEBCwUAMBUxEzAR
          BgNVBAMTCmt1YmVybmV0ZXMwHhcNMjAwODIzMTUwMjU0WhcNMzAwODIzMTUwMjU0
          WjAVMRMwEQYDVQQDEwprdWJlcm5ldGVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
          MIIBCgKCAQEAsFhppwhs5bT9YITxzPsPD7Zi2GMuMo2BJHRQIl+hQIrge1fw7xtA
          ax3SPNEvcfRDE5C3M62TRoXUwbRVe6yHqi6YjM2yDIBrm3iJOjwWlzK3IpUiuh1U
          4/Ip5PH2rTGOg+KErCSnvd4YlgT8pBQ5nOoPxXBBXtp/WcLaH6U9pYOwjkCOh+S7
          gUYrYY+gJAswQLb7PVcaNytIxiVpgs0WIQbtRfIl/lxRKUakNDQs+gqXFPkvnE7z
          lTZoRZaAGJKbiy87V7+ckLaNTsg5h9MEEGeVviFQw3fgyeg8G8V0hIxZPWjW9FFu
          0XQOxdWS95l8grYDXXvHRs5KcwSBpqfHIQIDAQABoyMwITAOBgNVHQ8BAf8EBAMC
          AQYwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAetLAw9tIYoiL
          B7ZcCJvbP0cvBbDZWQaQE7dq5dErBuoxkzpHUlD80RA2o7ZbzUUrqz6rDzecPjI9
          quFgaoX8QNEJ+D5T/hqeJ3N/i7U7fnn7fzaDZ/IL6LWGwDcfqVUcdGNyCQJ+h3XJ
          E4YccK+nsTDfKLV7MY5pR5UKfKtOAEktK8qq84NBgMdnFlhMiLgvkJMOKIvitw4T
          l2yaL7rlsyb4p4tj7ne2CQc+TnC664pT7QU/ShsttlK0eVeOIYHJfDmB8PXLVtbL
          IeT6eHLRg+LfPslgz26/h+daRmwoJ1ZQb3pfd1C/qaj/FJKXKzo5xg1hsx+tZAMD
          k0UukSY9ZQ==
          -----END CERTIFICATE-----
      k8s_master_uri: https://api.us-east-1.prod.milli-bank.com
      name: us-east-1.prod.milli-bank.com
      redirect_uri: https://login.us-east-1.prod.milli-bank.com/callback/my-cluster
      short_description: Milli Production Cluster
kind: ConfigMap
metadata:
  labels:
    app: platform-dex-k8s-authenticator
    chart: dex-k8s-authenticator-1.2.0
    env: prod
    heritage: Helm
    release: platform
  name: platform-dex-k8s-authenticator
  namespace: dex-k8s-auth
---
apiVersion: v1
data:
  config.yaml: |-
    issuer: https://dex.us-east-1.prod.milli-bank.com
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    frontend:
      theme: "coreos"
      issuer: "Example Co"
      issuerUrl: "https://example.com"
      logoUrl: https://example.com/images/logo-250x25.png
    expiry:
      signingKeys: "6h"
      idTokens: "24h"
    logger:
      level: debug
      format: json
    oauth2:
      responseTypes: ["code", "token", "id_token"]
      skipApprovalScreen: true
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: 3a00c0d01cdfd287f047 
        clientSecret: beb994a93d81cf4320716f38b34b1a07d84d5bc1 
        redirectURI: https://dex.us-east-1.prod.milli-bank.com/callback
        orgs:
        - name: gen6-ventures
    staticClients:
    - id: dex-k8s-authenticator
      name: "dex-k8s-authenticator"
      secret: "yPnRbu1MYW2OAFgYF13gkj9QMprhWAjBTKpKTO5mIuc5IE5X"
      redirectURIs:
      - https://login.us-east-1.prod.milli-bank.com/callback/my-cluster
    enablePasswordDB: False
    staticPasswords: []
kind: ConfigMap
metadata:
  labels:
    app: platform-dex
    chart: dex-1.2.0
    env: prod
    heritage: Helm
    release: platform
  name: platform-dex
  namespace: dex-rbac
