---  
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  externalUrl: http://prometheus.us-east-1.prod.milli-bank.com
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
  namespace: monitoring
spec:
  externalUrl: http://alertmanager.us-east-1.prod.milli-bank.com
---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KICBzbGFja19hcGlfdXJsOiAnaHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVERIVDFQV0IwL0IwMTVXMExIMUZCLzBiY3VVd2lMSTRNQjM1UU5ScEdYSlljZCcKcm91dGU6CiAgZ3JvdXBfYnk6IFsnYWxlcnRuYW1lJywgJ2FwcCcsICdqb2InXQogIGdyb3VwX3dhaXQ6IDMwcwogIGdyb3VwX2ludGVydmFsOiA1bQogIHJlcGVhdF9pbnRlcnZhbDogMWgKICByZWNlaXZlcjogJ3NsYWNrLW5vdGlmaWNhdGlvbnMnCiAgcm91dGVzOgogIC0gbWF0Y2g6CiAgICAgIGFsZXJ0bmFtZTogV2F0Y2hkb2cKICAgIHJlY2VpdmVyOiAnbnVsbCcKICAtIG1hdGNoOgogICAgICBzZXZlcml0eTogY3JpdGljYWwKICAgIHJlY2VpdmVyOiAnc2xhY2stbm90aWZpY2F0aW9ucycKaW5oaWJpdF9ydWxlczoKICAtIHNvdXJjZV9tYXRjaDoKICAgICAgc2V2ZXJpdHk6ICdjcml0aWNhbCcKICAgIHRhcmdldF9tYXRjaDoKICAgICAgc2V2ZXJpdHk6ICd3YXJuaW5nJwogICAgZXF1YWw6IFsnYWxlcnRuYW1lJywgJ2FwcCcsICdqb2InXQpyZWNlaXZlcnM6Ci0gbmFtZTogJ251bGwnCi0gbmFtZTogJ3NsYWNrLW5vdGlmaWNhdGlvbnMnCiAgcGFnZXJkdXR5X2NvbmZpZ3M6CiAgLSByb3V0aW5nX2tleTogJ1IwMjZHMTdYMFhJMVE3R1k5VEtRMFhFTVUxNDNZV1AzJwogIHNsYWNrX2NvbmZpZ3M6CiAgLSBzZW5kX3Jlc29sdmVkOiB0cnVlCiAgICBjb2xvcjogJ3t7IGlmIGVxIC5TdGF0dXMgImZpcmluZyIgfX1kYW5nZXJ7eyBlbHNlIH19Z29vZHt7IGVuZCB9fScKICAgIHRpdGxlOiAnW3t7IC5TdGF0dXMgfCB0b1VwcGVyIH19e3sgaWYgZXEgLlN0YXR1cyAiZmlyaW5nIiB9fTp7eyAuQWxlcnRzLkZpcmluZyB8IGxlbiB9fXt7IGVuZCB9fV0gUHJvbWV0aGV1cyBBbGVydHMgb24gYHByb2RgJwogICAgcHJldGV4dDogJ3t7IC5Db21tb25Bbm5vdGF0aW9ucy5zdW1tYXJ5IH19JwogICAgdGV4dDogfC0KICAgICAgIHt7IHJhbmdlIC5BbGVydHMgfX0KICAgICAgICAge3stIGlmIC5Bbm5vdGF0aW9ucy5zdW1tYXJ5IH19KkFsZXJ0Oioge3sgLkFubm90YXRpb25zLnN1bW1hcnkgfX0gLSBge3sgLkxhYmVscy5zZXZlcml0eSB9fWB7ey0gZW5kIH19CiAgICAgICAgICpEZXNjcmlwdGlvbjoqIHt7IC5Bbm5vdGF0aW9ucy5kZXNjcmlwdGlvbiB9fXt7IC5Bbm5vdGF0aW9ucy5tZXNzYWdlIH19CiAgICAgICAgICpHcmFwaDoqIDx7eyAuR2VuZXJhdG9yVVJMIH19fDpjaGFydF93aXRoX3Vwd2FyZHNfdHJlbmQ6Pnt7IGlmIG9yIC5Bbm5vdGF0aW9ucy5ydW5ib29rIC5Bbm5vdGF0aW9ucy5ydW5ib29rX3VybCB9fSAqUnVuYm9vazoqIDxodHRwczovL2dpdGh1Yi5jb20vMTFGU0NvbnN1bHRpbmcvcGxhdGZvcm0vdHJlZS9tYXN0ZXIvZG9jcy9BTEVSVFMubWQje3sgLkxhYmVscy5hbGVydG5hbWUgfX18OnNwaXJhbF9ub3RlX3BhZDo+e3sgZW5kIH19CiAgICAgICAgICpEZXRhaWxzOioKICAgICAgICAge3sgcmFuZ2UgLkxhYmVscy5Tb3J0ZWRQYWlycyB9fSAtICp7eyAuTmFtZSB9fToqIGB7eyAuVmFsdWUgfX1gCiAgICAgICAgIHt7IGVuZCB9fQogICAgICAge3sgZW5kIH19Cg== 
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: W2F1dGguYW5vbnltb3VzXQplbmFibGVkID0gdHJ1ZQpvcmdfcm9sZSA9IEFkbWluCltzZXJ2ZXJdCnJvb3RfdXJsID0gaHR0cDovL2dyYWZhbmEudXMtZWFzdC0xLnByb2QubWlsbGktYmFuay5jb20vCg== 
