---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: mino-reporting
  labels:
    app: mino-reporting
    db: "mino"
    auth: "okta"
  annotations:
    configmap.reloader.stakater.com/reload: "mino-reporting-env-vars"
    secret.reloader.stakater.com/reload: "milli-server-tls,rds-cert,mino-reporting-db-password"
spec:
  progressDeadlineSeconds: 140
  selector:
    matchLabels:
      app: mino-reporting
  replicas: 2
  template:
    metadata:
      labels:
        app: mino-reporting
        db: "mino"
        auth: "okta"
    spec:
      containers:
        - image: 850315125037.dkr.ecr.us-east-1.amazonaws.com/mino-reporting:latest
          name: mino-reporting
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: mino-reporting-env-vars
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mino-reporting-db-password
                  key: password
          ports:
            - containerPort: 8443
              name: https
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 75
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 75
            periodSeconds: 5
          resources:
            requests:
              cpu: "125m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
