apiVersion: v1
kind: Service
metadata:
  name: mino-reporting
  labels:
    app: mino-reporting
spec:
  ports:
    - port: 8443
      name: https
    - port: 8081
      name: http-actuator
  selector:
    app: mino-reporting
  type: ClusterIP
