apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - disruptionbudget.yaml
  - service.yaml
  - service-monitor.yaml

configMapGenerator:
  - name: mino-transactions-env-vars
    literals:
      - SENTRY_DSN=https://2b91fc7304e24c9db2d5f4e14a8dfeb2@sentry.io/1863168
  - name: mino-transactions-category-mappings
    files:
      - data/mino-transactions-category-mappings.yaml
  - name: mino-transactions-mcc-mappings
    files:
      - data/mino-transactions-mcc-mappings.yaml
