apiVersion: v1
kind: Service
metadata:
  name: mino-transactions
  labels:
    app: mino-transactions
    discoverable-swagger: enabled
spec:
  ports:
    - port: 8443
      name: https
    - port: 8081
      name: http-actuator
  selector:
    app: mino-transactions
  type: ClusterIP
