---
# Note that Postgres currently exists outside the K8 cluster. This merely provides an easy to use address.kind: Service
apiVersion: v1
kind: Service
metadata:
  name: mino-postgres
spec:
  type: ExternalName
  externalName: qa-us-east-1.cluster-cbjq3tjwvqw1.us-east-1.rds.amazonaws.com 
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  type: ExternalName
  externalName: stream-collector.jaeger.svc.cluster.local
---
# Note that ElastiCache currently exists outside the K8 cluster. This merely provides an easy to use address.kind: Service
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ExternalName
  externalName: clustercfg.qa-us-east-1.bmoam9.use1.cache.amazonaws.com 
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-schema-registry
spec:
  type: ExternalName
  externalName: platform-cp-schema-registry.kafka.svc.cluster.local
