---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-transactions-mx-api-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - mx-api-prod
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-transactions-marqeta-password
secretDescriptor:
  backendType: secretsManager
  data:
    - key: marqeta-password-prod
      name: password
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-db-transactions-user
secretDescriptor:
  backendType: secretsManager
  data:
    - key: transactions-db-password-prod
      name: PASSWORD
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-transactions-client-credentials-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - transactions-client-credentials-prod
