---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-accounts-marqeta-password
secretDescriptor:
  backendType: secretsManager
  data:
    - key: marqeta-password-prod
      name: password
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-accounts-db-password
secretDescriptor:
  backendType: secretsManager
  data:
    - key: accounts-db-password-prod
      name: password
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-accounts-plaid-api
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - plaid-api-prod
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-accounts-client-credentials-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - accounts-client-credentials-prod
