apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - disruptionbudget.yaml
  - service.yaml
  - service-monitor.yaml

configMapGenerator:
  - name: mino-registrations-env-vars
    literals:
      - SENTRY_DSN=https://c836b854b2354dd58e98af0ae8311e76@o257648.ingest.sentry.io/5378125
      - GEN6_REGISTRATIONS_JWE_CONFIG_KEYS_0_IS_PRIMARY=true
      - GEN6_REGISTRATIONS_JWE_CONFIG_KEYS_0_KEY_ID=cb914c22-a281-4e1d-bc21-b11e2f05a433
      - APNS_HOST=api.push.apple.com
      - APNS_PORT=443
