apiVersion: v1
kind: Service
metadata:
  name: mino-api-tests
  labels:
    app: mino-api-tests
spec:
  ports:
    - port: 8443
      name: https
    - port: 8081
      name: http-actuator
  selector:
    app: mino-api-tests
  type: ClusterIP
