---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: mino-api-gateway
  labels:
    app: mino-api-gateway
    auth: "okta"
  annotations:
    secret.reloader.stakater.com/reload: "milli-server-tls,mino-api-gateway-twilio-api-secret,mino-api-gateway-client-credentials-secret"
    configmap.reloader.stakater.com/reload: "mino-api-gateway-env-vars"
spec:
  progressDeadlineSeconds: 140
  selector:
    matchLabels:
      app: mino-api-gateway
  replicas: 2
  template:
    metadata:
      labels:
        app: mino-api-gateway
        auth: "okta"
    spec:
      containers:
        - image: 850315125037.dkr.ecr.us-east-1.amazonaws.com/mino-api-gateway:latest
          name: mino-api-gateway
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: mino-api-gateway-env-vars
          env:
            - name: TWILIO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mino-api-gateway-twilio-api-secret
                  key: token
            - name: CLIENT_CREDENTIALS_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: mino-api-gateway-client-credentials-secret
                  key: client-id
            - name: CLIENT_CREDENTIALS_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mino-api-gateway-client-credentials-secret
                  key: client-secret
            - name: CLIENT_CREDENTIALS_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: mino-api-gateway-client-credentials-secret
                  key: audience
            - name: CLIENT_CREDENTIALS_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: mino-api-gateway-client-credentials-secret
                  key: domain
          ports:
            - containerPort: 8443
              name: https
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 45
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            requests:
              cpu: "125m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
