---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: mino-onboarding
spec:
  selector:
    matchLabels:
      app: mino-onboarding
  template:
    spec:
      containers:
        - name: mino-onboarding
          env:
            - name: POSTGRES_USER
              value: onboarding
              valueFrom: null
