---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-onboarding-itunes-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - onboarding-itunes-prod
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-onboarding-client-credentials-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - onboarding-client-credentials-prod
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-onboarding-intercom-token
secretDescriptor:
  backendType: secretsManager
  data:
    - key: intercom-token-prod
      name: token
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-db-onboarding-user
secretDescriptor:
  backendType: secretsManager
  data:
    - key: onboarding-db-password-prod
      name: PASSWORD
