---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: mino-helios-auth0-client-secret
secretDescriptor:
  backendType: secretsManager
  data:
    - key: helios-auth0-client-secret-prod
      name: password
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: mino-helios-auth0-secret
secretDescriptor:
  backendType: secretsManager
  data:
    - key: helios-auth0-secret-prod
      name: password
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: mino-helios-sentry-auth-token
secretDescriptor:
  backendType: secretsManager
  data:
    - key: helios-sentry-auth-token-prod
      name: password
