{
 "title": "Development Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "organization", "label": "Organization", "query": "gen6-ventures" },
   { "name": "repository", "label": "Repository", "query": "infra" }
  ]
 },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application Availability (30d)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100-\n((count(http_server_requests_seconds_max{exception!=\"None\",outcome!=\"SUCCESS\"} OR on() vector(0))\n+(count(http_server_requests_seconds_max{outcome=\"SUCCESS\"} > 0.3) OR on() vector(0)))\n/\n(count(http_server_requests_seconds_max{exception=\"None\",outcome=\"SUCCESS\"} <= 0.3) OR on() vector(0))\n)*100"
    }
   ]
  },
  {
   "title": "Platform Availability (30d)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"all\"}"
    }
   ]
  },
  {
   "title": "Application Error Budget (30d)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((100-\n((count(http_server_requests_seconds_max{exception!=\"None\",outcome!=\"SUCCESS\"} OR on() vector(0))\n+(count(http_server_requests_seconds_max{outcome=\"SUCCESS\"} > 0.3) OR on() vector(0)))\n/\n(count(http_server_requests_seconds_max{exception=\"None\",outcome=\"SUCCESS\"} <= 0.3) OR on() vector(0))\n)*100)-95)/(100-95))*100"
    }
   ]
  },
  {
   "title": "Platform Error Budget (30d)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((100*apiserver_request:availability30d{verb=\"all\"})-99.999)/(100-99.999))*100"
    }
   ]
  },
  { "title": "Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Frontend Releases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "owner": "$organization", "repository": "mino-mobile" }
   ]
  },
  {
   "title": "Pull Requests Merged",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "options": { "query": "base:develop is:merged", "timeField": 2 }, "owner": "$organization", "repository": "mino-mobile" }
   ]
  },
  {
   "title": "PR: Average Time in Integration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "options": { "query": "base:develop is:merged", "timeField": 2 }, "owner": "$organization", "repository": "mino-mobile" }
   ]
  },
  {
   "title": "Release: Average Time in QA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "options": { "query": "base:master is:merged", "timeField": 2 }, "owner": "$organization", "repository": "mino-mobile" }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Backend Releases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "owner": "$organization", "repository": "$repository" }
   ]
  },
  {
   "title": "Dev -> Integration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "options": {
      "query": "is:merged label:\"release/int\"",
      "timeField": 2
     },
     "owner": "$organization",
     "repository": "$repository"
    }
   ]
  },
  {
   "title": "Integration -> QA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "options": {
      "query": "is:merged label:\"release/qa\"",
      "timeField": 2
     },
     "owner": "$organization",
     "repository": "$repository"
    }
   ]
  },
  {
   "title": "QA -> Production (Standard)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "options": {
      "query": "label:\"release/milli-prod\" is:merged",
      "timeField": 2
     },
     "owner": "$organization",
     "repository": "$repository"
    }
   ]
  },
  {
   "title": "QA -> Production (Ad-hoc)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "options": {
      "query": "label:\"adhoc-release/prod\" is:merged",
      "timeField": 2
     },
     "owner": "$organization",
     "repository": "$repository"
    }
   ]
  },
  {
   "title": "PR: Average Time in Integration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "options": {
      "query": "label:\"release/qa\" is:merged",
      "timeField": 2
     },
     "owner": "$organization",
     "repository": "$repository"
    }
   ]
  },
  {
   "title": "Release: Average Time in QA (Standard)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "options": {
      "query": "label:\"release/milli-prod\"",
      "timeField": 2
     },
     "owner": "$organization",
     "repository": "$repository"
    }
   ]
  },
  {
   "title": "Release: Average Time in QA (Ad-hoc)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "options": {
      "query": "label:\"adhoc-release/prod\" is:merged",
      "timeField": 2
     },
     "owner": "$organization",
     "repository": "$repository"
    }
   ]
  }
 ]
}