---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-notification-twilio-api-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - twillio-api-prod
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-db-notification-user
secretDescriptor:
  backendType: secretsManager
  data:
    - key: notification-db-password-prod
      name: PASSWORD
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-notification-client-credentials-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - notification-client-credentials-prod

