apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-transfer-rules-db-password
secretDescriptor:
  backendType: secretsManager
  data:
    - key: transfer-rules-db-password-qa
      name: password
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-transfer-rules-client-credentials-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - transfer-rules-client-credentials-qa
