---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: mino-plaid-mock
  labels:
    app: mino-plaid-mock
    auth: "okta"
  annotations:
    configmap.reloader.stakater.com/reload: "mino-plaid-mock-env-vars"
    secret.reloader.stakater.com/reload: "milli-server-tls,mino-plaid-mock-api-password,mino-plaid-mock-db-password"
spec:
  progressDeadlineSeconds: 140
  selector:
    matchLabels:
      app: mino-plaid-mock
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mino-plaid-mock
        auth: "okta"
    spec:
      containers:
        - image: 850315125037.dkr.ecr.us-east-1.amazonaws.com/mino-plaid-mock:latest
          name: mino-plaid-mock
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: mino-plaid-mock-env-vars
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mino-plaid-mock-db-password
                  key: password
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mino-plaid-mock-api-password
                  key: password
          ports:
            - containerPort: 8443
              name: https
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 45
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "125m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
