apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- grafana-api-tests-dashboard.yaml
patchesStrategicMerge:
- prometheus-custom.yaml
- elasticsearch-custom.yaml
- grafana-custom.yaml
