apiVersion: v1
data:
  blackbox.yaml: |
    modules:
      tcp_connect:
        prober: tcp
      icmp:
        prober: icmp
      http_2xx:
        http:
          no_follow_redirects: false
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2
          valid_status_codes: []
        prober: http
        timeout: 5s
kind: ConfigMap
metadata:
  labels:
    app: prometheus-blackbox-exporter
  name: prometheus-blackbox-exporter
  namespace: monitoring
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-blackbox-exporter
  name: prometheus-blackbox-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9115
    protocol: TCP
  selector:
    app: prometheus-blackbox-exporter
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-blackbox-exporter
  name: prometheus-blackbox-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-blackbox-exporter
  template:
    metadata:
      labels:
        app: prometheus-blackbox-exporter
    spec:
      containers:
      - args:
        - --config.file=/config/blackbox.yaml
        image: prom/blackbox-exporter:v0.19.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: http
        name: blackbox-exporter
        ports:
        - containerPort: 9115
          name: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
        resources: {}
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - mountPath: /config
          name: config
      - args:
        - --volume-dir=/etc/config
        - --webhook-url=http://localhost:9115/-/reload
        image: jimmidyson/configmap-reload:v0.2.2
        imagePullPolicy: IfNotPresent
        name: configmap-reload
        resources: {}
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
        volumeMounts:
        - mountPath: /etc/config
          name: config
          readOnly: true
      restartPolicy: Always
      volumes:
      - configMap:
          name: prometheus-blackbox-exporter
        name: config
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
    release: prometheus
  name: test-probe
  namespace: monitoring
spec:
  module: http_2xx
  prober:
    url: prometheus-blackbox-exporter.monitoring.svc:9115
  targets:
    staticConfig:
      labels:
        environment: prometheus.io
      static:
      - https://www.google.com
