---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: mino-notification
  labels:
    app: mino-notification
    db: "mino"
    auth: "okta"
  annotations:
    secret.reloader.stakater.com/reload: "milli-server-tls,mino-notification-twilio-api-secret"
    configmap.reloader.stakater.com/reload: "mino-notification-env-vars"
spec:
  progressDeadlineSeconds: 140
  selector:
    matchLabels:
      app: mino-notification
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mino-notification
        db: "mino"
        auth: "okta"
    spec:
      containers:
        - image: 850315125037.dkr.ecr.us-east-1.amazonaws.com/mino-notification:latest
          name: mino-notification
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: mino-notification-env-vars
          env:
            - name: TWILIO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mino-notification-twilio-api-secret
                  key: token
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mino-db-notification-user
                  key: PASSWORD
            - name: CLIENT_CREDENTIALS_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: mino-notification-client-credentials-secret
                  key: domain
            - name: CLIENT_CREDENTIALS_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: mino-notification-client-credentials-secret
                  key: client-id
            - name: CLIENT_CREDENTIALS_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mino-notification-client-credentials-secret
                  key: client-secret
            - name: CLIENT_CREDENTIALS_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: mino-notification-client-credentials-secret
                  key: audience
          ports:
            - containerPort: 8443
              name: https
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 75
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 75
            periodSeconds: 5
          resources:
            requests:
              cpu: "125m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
