apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-test-capabilities-marqeta-password
secretDescriptor:
  backendType: secretsManager
  data:
    - key: marqeta-password-staging
      name: password
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-test-capabilities-plaid-api
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - plaid-api-sandbox
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-test-capabilities-api-password
secretDescriptor:
  backendType: secretsManager
  data:
    - key: test-capabilities-api-password
      name: password
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-test-capabilities-client-credentials-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - test-capabilities-client-credentials-qa
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-test-capabilities-jwt-signing-key-secret
secretDescriptor:
  backendType: secretsManager
  data:
    - key: test-capabilities-jwt-signing-key-qa
      name: private-key
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-test-capabilities-jwe-secret-key
secretDescriptor:
  backendType: secretsManager
  data:
    - key: registrations-jwe-secret-key-qa-v1
      name: jwe-secret-key
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-test-capabilities-mino-tools-client-credentials-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - mino-tools-client-credentials-qa
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-test-capabilities-basic-auth-ingress
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - mino-test-capabilities-basic-auth-ingress
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-test-capabilities-iv-secret-key
secretDescriptor:
  backendType: secretsManager
  data:
    - key: registrations-iv-secret-key-qa
      name: iv-secret-key
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-test-capabilities-webhook-fnbo-secret
secretDescriptor:
  backendType: secretsManager
  data:
    - key: fnbo-webhook-qa
      name: secret
