apiVersion: v1
kind: ConfigMap
metadata:
  name: mino-ops-ui-env-json
data:
  env.admin.json: |
    {
      "ADMIN_API_URL": "https://mino-api.us-east-1.prod.milli-bank.com/admin-api/graphql",
      "AUTH0_CLIENT_ID_OPS_UI": "eBOLaY5uKKpiIiLnHKmSnmJp9a3L3Htg",
      "AUTH0_DOMAIN": "mino-prod.auth0.com"
    }
