---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-registrations-apns-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - apns-signing-key

---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-registrations-jwe-secret-key-v1
secretDescriptor:
  backendType: secretsManager
  data:
    - key: registrations-jwe-secret-key-qa-v1
      name: jwe-secret-key
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-registrations-client-credentials-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - registration-client-credentials-qa
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-registrations-iv-secret-key
secretDescriptor:
  backendType: secretsManager
  data:
    - key: registrations-iv-secret-key-qa
      name: iv-secret-key
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-registrations-apns-cert
secretDescriptor:
  backendType: secretsManager
  data:
    - key: registrations-apns-cert-qa
      property: crt
      name: crt
    - key: registrations-apns-cert-qa
      property: key
      name: key
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-registrations-fcm-service-account
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - registrations-fcm-service-account-qa
