---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: mino-disclosures
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mino-disclosures
  template:
    spec:
      containers:
        - name: mino-disclosures
          env:
            - name: POSTGRES_USER
              value: disclosures
              valueFrom: null
