---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: mino-kyc
  labels:
    app: mino-kyc
    auth: "okta"
  annotations:
    configmap.reloader.stakater.com/reload: "mino-kyc-env-vars"
    secret.reloader.stakater.com/reload: "milli-server-tls,mino-kyc-marqeta-password,mino-kyc-client-credentials-secret"
spec:
  progressDeadlineSeconds: 140
  selector:
    matchLabels:
      app: mino-kyc
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mino-kyc
        auth: "okta"
    spec:
      containers:
        - image: 850315125037.dkr.ecr.us-east-1.amazonaws.com/mino-kyc:latest
          name: mino-kyc
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: mino-kyc-env-vars
          env:
            - name: MARQETA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mino-kyc-marqeta-password
                  key: password
            - name: CLIENT_CREDENTIALS_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: mino-kyc-client-credentials-secret
                  key: domain
            - name: CLIENT_CREDENTIALS_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: mino-kyc-client-credentials-secret
                  key: client-id
            - name: CLIENT_CREDENTIALS_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mino-kyc-client-credentials-secret
                  key: client-secret
            - name: CLIENT_CREDENTIALS_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: mino-kyc-client-credentials-secret
                  key: audience
          ports:
            - containerPort: 8443
              name: https
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 45
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "125m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
