apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - disruptionbudget.yaml
  - service.yaml
  - service-monitor.yaml

configMapGenerator:
  - name: mino-kyc-env-vars
    literals:
      - SWAGGER_ENABLED=false
      - SENTRY_DSN=https://72ed93009aad46ed9210cabde7e4c6ac@o257648.ingest.sentry.io/5224874
