apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: namespace-env-preset
spec:
  env:
    - name: APP_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
