apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - disruptionbudget.yaml
  - service.yaml
  - service-monitor.yaml

configMapGenerator:
  - name: mino-identity-env-vars
    literals:
      - SWAGGER_ENABLED=false
      - SENTRY_DSN=https://94bfea77717d4ea2b711536708b1a69a@sentry.io/2098151
