apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mino-insights
spec:
  selector:
    matchLabels:
      app: mino-insights
  endpoints:
    - port: http-actuator
      path: '/actuator/prometheus'
      interval: 10s
      honorLabels: true
