---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dex-cluster-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-readonly
subjects:
  - kind: Group
    name: "gen6-ventures:Engineering Team"
  - kind: Group
    name: "gen6-ventures:QA"
  - kind: Group
    name: "gen6-ventures:Front End"
  - kind: Group
    name: "gen6-ventures:Back End"
  - kind: Group
    name: "gen6-ventures:Operations"
  - kind: Group
    name: "gen6-ventures:Security"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    app: dex-k8s-authenticator
    chart: dex-k8s-authenticator-1.2.0
    env: prod
    heritage: Helm
    release: platform
  name: platform-dex-k8s-authenticator
  namespace: dex-k8s-auth
spec:
  rules:
  - host: login.int.us-east-1.dev.gen6bk.com
    http:
      paths:
      - backend:
          serviceName: platform-dex-k8s-authenticator
          servicePort: 5555
        path: /
  tls:
  - hosts:
    - login.int.us-east-1.dev.gen6bk.com
    secretName: cert-auth-login
---
apiVersion: v1
data:
  config.yaml: |-
    listen: http://0.0.0.0:5555
    web_path_prefix: /
    debug: false
    clusters:
    - client_id: dex-k8s-authenticator
      client_secret: yPnRbu1MYW2OAFgYF13gkj9QMprhWAjBTKpKTO5mIuc5IE5X
      description: Milli Int Cluster
      issuer: https://dex.int.us-east-1.dev.gen6bk.com
      k8s_ca_pem: |-
        -----BEGIN CERTIFICATE-----
        MIIC0zCCAbugAwIBAgIMFhRx1MRWocho2DHOMA0GCSqGSIb3DQEBCwUAMBUxEzAR
        BgNVBAMTCmt1YmVybmV0ZXMwHhcNMjAwNTMwMTQyODQ3WhcNMzAwNTMwMTQyODQ3
        WjAVMRMwEQYDVQQDEwprdWJlcm5ldGVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
        MIIBCgKCAQEAnEepdBeNnqYLxVFCMaBwR3sPRVJO6RR3YyJ1hzNuJt8uw4gLtsbU
        OLtwzhJ8qB7OlY23BrNenngwp414HBwkjy1GqrF5C1/ijwlf8itY1bYseti+dvxT
        pGt3GYsdXoc4Lft0cotFPJV3EOmja2XvGiyori0DRPinqRV3iSiQsGaqtSf2ctpq
        izTSrKlH5cHmT+QuYkZqqdTn0t+j4w7hSNmGA8yQekcxtmZ1Swo5uA5nl8iQE/Ok
        5WMJaqYNVHAz0lSgaGSue5yJmRGQhrzTLxlf9wXcKFXVuvHe7HL9RphAzOOzJp3V
        ZD9tsLLmjEANL7CxDvhBIy/lTcuN+oZdFQIDAQABoyMwITAOBgNVHQ8BAf8EBAMC
        AQYwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAMOWhfugAiIaW
        c1w61e0UIzgSSpEYXn8zcYnopgZhcC+7N/S3soR8Y8x89IALFHwN5DJvtY0/gVFe
        JWQZ76kD9TkEGS4j2BI6I0SV9524ORU7Hwec4x8vCC+iKPzMjRVDqvH7PLb1WiIE
        Iye0REVGNjrSikyQwqknJYQ3+De/4uNDOC4Br12H53cyXy+2BHhNaM2YS/eUzQlU
        Q8OO4txOmBJEinQjp8SUAwWaN0xYcv4u1dEpYMN1hDF3DVDhfo9dfT7okpaOm98o
        SCtnqSSvPf56CT1wRxnd2J71PgC8r3tDjnQzyPCT97Vf8JzG+uZxgKIwq4x7fYWb
        VgmQtwZ0Fw==
        -----END CERTIFICATE-----
      k8s_master_uri: https://api.int.us-east-1.dev.gen6bk.com
      name: int.us-east-1.dev.gen6bk.com
      redirect_uri: https://login.int.us-east-1.dev.gen6bk.com/callback/my-cluster
      short_description: Milli Int Cluster
kind: ConfigMap
metadata:
  labels:
    app: platform-dex-k8s-authenticator
    chart: dex-k8s-authenticator-1.2.0
    env: prod
    heritage: Helm
    release: platform
  name: platform-dex-k8s-authenticator
  namespace: dex-k8s-auth
---
apiVersion: v1
data:
  config.yaml: |-
    issuer: https://dex.int.us-east-1.dev.gen6bk.com
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    frontend:
      theme: "coreos"
      issuer: "Example Co"
      issuerUrl: "https://example.com"
      logoUrl: https://example.com/images/logo-250x25.png
    expiry:
      signingKeys: "6h"
      idTokens: "24h"
    logger:
      level: debug
      format: json
    oauth2:
      responseTypes: ["code", "token", "id_token"]
      skipApprovalScreen: true
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: 39f5a0becceb168ac949 
        clientSecret: 471dc2b557963c702d9c10ddbd5bcf6ac6e1f661 
        redirectURI: https://dex.int.us-east-1.dev.gen6bk.com/callback
        orgs:
        - name: gen6-ventures
    staticClients:
    - id: dex-k8s-authenticator
      name: "dex-k8s-authenticator"
      secret: "yPnRbu1MYW2OAFgYF13gkj9QMprhWAjBTKpKTO5mIuc5IE5X"
      redirectURIs:
      - https://login.int.us-east-1.dev.gen6bk.com/callback/my-cluster
    enablePasswordDB: False
    staticPasswords: []
kind: ConfigMap
metadata:
  labels:
    app: platform-dex
    chart: dex-1.2.0
    env: prod
    heritage: Helm
    release: platform
  name: platform-dex
  namespace: dex-rbac
