---
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cluster
  namespace: kafka
spec:
  kafkaExporter: {}
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    resources:
      requests:
        memory: 2Gi
        cpu: 300m
      limits:
        memory: 4Gi
        cpu: 2
    jvmOptions:
      -Xms: 1024m
      -Xmx: 2048m
    rack:
      topologyKey: topology.kubernetes.io/zone
    config:
      log.message.format.version: "2.5"
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
      auto.create.topics.enable: false
    listeners:
      plain: {}
      tls: {}
    replicas: 3
    storage:
      type: jbod
      volumes:
      - deleteClaim: false
        id: 0
        size: 32Gi
        class: stable
        type: persistent-claim
    version: 2.5.0
  zookeeper:
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 1
    replicas: 3
    storage:
      deleteClaim: false
      size: 32Gi
      class: stable 
      type: persistent-claim
