---  
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  externalUrl: http://prometheus.int.us-east-1.dev.gen6bk.com
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
  namespace: monitoring
spec:
  externalUrl: http://alertmanager.int.us-east-1.dev.gen6bk.com
---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KICBzbGFja19hcGlfdXJsOiAnaHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVERIVDFQV0IwL0IwMTRMOVVONTZXL005NDd4S2pPT3pteEc2MEZBUlZTNmtPNycKcm91dGU6CiAgZ3JvdXBfYnk6IFsnYWxlcnRuYW1lJywgJ2FwcCcsICdqb2InXQogIGdyb3VwX3dhaXQ6IDMwcwogIGdyb3VwX2ludGVydmFsOiA1bQogIHJlcGVhdF9pbnRlcnZhbDogMWgKICByZWNlaXZlcjogJ3NsYWNrLW5vdGlmaWNhdGlvbnMnCiAgcm91dGVzOgogIC0gbWF0Y2g6CiAgICAgIGFsZXJ0bmFtZTogV2F0Y2hkb2cKICAgIHJlY2VpdmVyOiAnbnVsbCcKICAtIG1hdGNoOgogICAgICBzZXZlcml0eTogY3JpdGljYWwKICAgIHJlY2VpdmVyOiAnc2xhY2stbm90aWZpY2F0aW9ucycKaW5oaWJpdF9ydWxlczoKICAtIHNvdXJjZV9tYXRjaDoKICAgICAgc2V2ZXJpdHk6ICdjcml0aWNhbCcKICAgIHRhcmdldF9tYXRjaDoKICAgICAgc2V2ZXJpdHk6ICd3YXJuaW5nJwogICAgZXF1YWw6IFsnYWxlcnRuYW1lJywgJ2FwcCcsICdqb2InXQpyZWNlaXZlcnM6Ci0gbmFtZTogJ251bGwnCi0gbmFtZTogJ3NsYWNrLW5vdGlmaWNhdGlvbnMnCiAgcGFnZXJkdXR5X2NvbmZpZ3M6CiAgLSByb3V0aW5nX2tleTogJ1IwMjZHMTdYMFhJMVE3R1k5VEtRMFhFTVUxNDNZV1AzJwogIHNsYWNrX2NvbmZpZ3M6CiAgLSBzZW5kX3Jlc29sdmVkOiB0cnVlCiAgICBjb2xvcjogJ3t7IGlmIGVxIC5TdGF0dXMgImZpcmluZyIgfX1kYW5nZXJ7eyBlbHNlIH19Z29vZHt7IGVuZCB9fScKICAgIHRpdGxlOiAnW3t7IC5TdGF0dXMgfCB0b1VwcGVyIH19e3sgaWYgZXEgLlN0YXR1cyAiZmlyaW5nIiB9fTp7eyAuQWxlcnRzLkZpcmluZyB8IGxlbiB9fXt7IGVuZCB9fV0gUHJvbWV0aGV1cyBBbGVydHMgb24gYGludGAnCiAgICBwcmV0ZXh0OiAne3sgLkNvbW1vbkFubm90YXRpb25zLnN1bW1hcnkgfX0nCiAgICB0ZXh0OiB8LQogICAgICAge3sgcmFuZ2UgLkFsZXJ0cyB9fQogICAgICAgICB7ey0gaWYgLkFubm90YXRpb25zLnN1bW1hcnkgfX0qQWxlcnQ6KiB7eyAuQW5ub3RhdGlvbnMuc3VtbWFyeSB9fSAtIGB7eyAuTGFiZWxzLnNldmVyaXR5IH19YHt7LSBlbmQgfX0KICAgICAgICAgKkRlc2NyaXB0aW9uOioge3sgLkFubm90YXRpb25zLmRlc2NyaXB0aW9uIH19e3sgLkFubm90YXRpb25zLm1lc3NhZ2UgfX0KICAgICAgICAgKkdyYXBoOiogPHt7IC5HZW5lcmF0b3JVUkwgfX18OmNoYXJ0X3dpdGhfdXB3YXJkc190cmVuZDo+e3sgaWYgb3IgLkFubm90YXRpb25zLnJ1bmJvb2sgLkFubm90YXRpb25zLnJ1bmJvb2tfdXJsIH19ICpSdW5ib29rOiogPGh0dHBzOi8vZ2l0aHViLmNvbS8xMUZTQ29uc3VsdGluZy9wbGF0Zm9ybS90cmVlL21hc3Rlci9kb2NzL0FMRVJUUy5tZCN7eyAuTGFiZWxzLmFsZXJ0bmFtZSB9fXw6c3BpcmFsX25vdGVfcGFkOj57eyBlbmQgfX0KICAgICAgICAgKkRldGFpbHM6KgogICAgICAgICB7eyByYW5nZSAuTGFiZWxzLlNvcnRlZFBhaXJzIH19IC0gKnt7IC5OYW1lIH19OiogYHt7IC5WYWx1ZSB9fWAKICAgICAgICAge3sgZW5kIH19CiAgICAgICB7eyBlbmQgfX0K 
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: W2F1dGguYW5vbnltb3VzXQplbmFibGVkID0gdHJ1ZQpvcmdfcm9sZSA9IEFkbWluCltzZXJ2ZXJdCnJvb3RfdXJsID0gaHR0cDovL2dyYWZhbmEuaW50LmRldi5nZW42YmsuY29tLwo=

