---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-sonatype-nexus
  namespace: sonatype-nexus
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-sonatype-nexus
  namespace: sonatype-nexus
subjects:
- kind: ServiceAccount
  name: platform-sonatype-nexus
  namespace: sonatype-nexus
roleRef:
  kind: Role
  name: platform-sonatype-nexus
  apiGroup: rbac.authorization.k8s.io
