apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: milli-server-tls
spec:
  secretName: milli-server-tls
  issuerRef:
    name: milli-server
    kind: Issuer
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: milli-server-cert-keystore-password
        key: password
  commonName: "*.prod.svc.cluster.local"
  dnsNames:
    - "*.prod.svc.cluster.local"
