---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: mino-transfer-rules
  labels:
    app: mino-transfer-rules
    db: "mino"
    auth: "okta"
  annotations:
    configmap.reloader.stakater.com/reload: "mino-transfer-rules-env-vars"
    secret.reloader.stakater.com/reload: "milli-server-tls,rds-cert,mino-transfer-rules-db-password,mino-transfer-rules-client-credentials-secret"
spec:
  progressDeadlineSeconds: 140
  selector:
    matchLabels:
      app: mino-transfer-rules
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mino-transfer-rules
        db: "mino"
        auth: "okta"
    spec:
      containers:
        - image: 850315125037.dkr.ecr.us-east-1.amazonaws.com/mino-transfer-rules:latest
          name: mino-transfer-rules
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: mino-transfer-rules-env-vars
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mino-transfer-rules-db-password
                  key: password
            - name: CLIENT_CREDENTIALS_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: mino-transfer-rules-client-credentials-secret
                  key: domain
            - name: CLIENT_CREDENTIALS_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: mino-transfer-rules-client-credentials-secret
                  key: client-id
            - name: CLIENT_CREDENTIALS_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mino-transfer-rules-client-credentials-secret
                  key: client-secret
            - name: CLIENT_CREDENTIALS_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: mino-transfer-rules-client-credentials-secret
                  key: audience
          ports:
            - containerPort: 8443
              name: https
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 75
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 75
            periodSeconds: 5
          resources:
            requests:
              cpu: "125m"
              memory: "768Mi"
            limits:
              cpu: "1000m"
              memory: "1536Mi"
