apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postgres.db.movetokube.com
spec:
  group: db.movetokube.com
  names:
    kind: Postgres
    listKind: PostgresList
    plural: postgres
    singular: postgres
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Postgres is the Schema for the postgres API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PostgresSpec defines the desired state of Postgres
          properties:
            database:
              type: string
            dropOnDelete:
              type: boolean
            extensions:
              items:
                type: string
              type: array
            masterRole:
              type: string
            schemas:
              items:
                type: string
              type: array
          required:
          - database
          type: object
        status:
          description: PostgresStatus defines the observed state of Postgres
          properties:
            extensions:
              items:
                type: string
              type: array
            roles:
              description: PostgresRoles stores the different group roles for database
              properties:
                owner:
                  type: string
                reader:
                  type: string
                writer:
                  type: string
              required:
              - owner
              - reader
              - writer
              type: object
            schemas:
              items:
                type: string
              type: array
            succeeded:
              type: boolean
          required:
          - roles
          - succeeded
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postgresusers.db.movetokube.com
spec:
  group: db.movetokube.com
  names:
    kind: PostgresUser
    listKind: PostgresUserList
    plural: postgresusers
    singular: postgresuser
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PostgresUser is the Schema for the postgresusers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PostgresUserSpec defines the desired state of PostgresUser
          properties:
            database:
              type: string
            privileges:
              type: string
            role:
              type: string
            secretName:
              type: string
          required:
          - database
          - role
          - secretName
          type: object
        status:
          description: PostgresUserStatus defines the observed state of PostgresUser
          properties:
            databaseName:
              type: string
            postgresGroup:
              type: string
            postgresLogin:
              type: string
            postgresRole:
              type: string
            succeeded:
              type: boolean
          required:
          - databaseName
          - postgresGroup
          - postgresLogin
          - postgresRole
          - succeeded
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ext-postgres-operator
  namespace: postgres-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ext-postgres-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - apps
  resourceNames:
  - ext-postgres-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - db.movetokube.com
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ext-postgres-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ext-postgres-operator
subjects:
- kind: ServiceAccount
  name: ext-postgres-operator
  namespace: postgres-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-postgres-operator
  namespace: postgres-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ext-postgres-operator
  template:
    metadata:
      labels:
        name: ext-postgres-operator
    spec:
      containers:
      - command:
        - postgres-operator
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: ext-postgres-operator
        envFrom:
        - secretRef:
            name: ext-postgres-operator
        image: movetokube/postgres-operator
        imagePullPolicy: Always
        name: ext-postgres-operator
      serviceAccountName: ext-postgres-operator
