---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: mino-identity
spec:
  replicas: 0
  selector:
    matchLabels:
      app: mino-identity
  template:
    spec:
      containers:
        - name: mino-identity
          env:
            - name: OKTA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mino-identity-okta-api-key
                  key: apikey
