---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-identity-intercom-token
secretDescriptor:
  backendType: secretsManager
  data:
    - key: intercom-token-staging
      name: token
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-identity-client-credentials-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - identity-client-credentials-staging
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-identity-okta-api-key
secretDescriptor:
  backendType: secretsManager
  data:
    - key: okta-api-key-int
      name: apikey
