# Secret containing the custom CA certificate used to sign the server certificates
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: milli-server-ca
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - milli-server-ca-staging
---
# Secret containing the password to use when creating a P12 file containing server certificates
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: milli-server-cert-keystore-password
secretDescriptor:
  backendType: secretsManager
  data:
    - key: milli-server-cert-keystore-password-staging
      name: password
