apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-insights-db-password
secretDescriptor:
  backendType: secretsManager
  data:
    - key: insights-db-password-staging
      name: password
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-insights-client-credentials-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - insights-client-credentials-staging
