---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dex-qa-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-readwriteqa
subjects:
- kind: Group
  name: gen6-ventures:QA
- kind: Group
  name: "gen6-ventures:Back End"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-readwriteqa
rules:
  - apiGroups:
      - ""
      - "apps"
    resources:
      - "deployments"
    verbs: 
      - "get"
      - "list"
      - "watch"
      - "edit"
      - "update"
      - "patch"
  - apiGroups: 
      - ""
    resources: 
      - "pods/exec"
      - "pods/portforward"
      - "pods"
    verbs: 
      - "get"
      - "list"
      - "create"
      - "delete"
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
      - storage.k8s.io
    resources:
      - componentstatuses
      - configmaps
      - cronjobs
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - ingresses
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - pods/log
      - pods/exec
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - secrets
      - serviceaccounts
      - services
      - statefulsets
      - storageclasses
      - clusterroles
      - roles
    verbs:
      - get
      - watch
      - list
  - nonResourceURLs: ["*"]
    verbs:
      - get
      - watch
      - list
