---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: stable
provisioner: kubernetes.io/aws-ebs 
reclaimPolicy: Retain
parameters:
    fsType: ext4
    type: gp2
    encrypted: "true"
allowVolumeExpansion: true
volumeBindingMode: Immediate
