apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: ext-postgres-operator
  namespace: postgres-operator
type: Opaque
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - qa-db-admin-dboperator
