---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
  namespace: tekton-pipelines
secrets:
- name: git-ssh-key
- name: git-web-key
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx-internal"
    nginx.ingress.kubernetes.io/auth-signin: https://auth.qa.us-east-1.dev.gen6bk.com/oauth2/start?rd=https%3A%2F%2F$host$request_uri
    nginx.ingress.kubernetes.io/auth-url: https://auth.qa.us-east-1.dev.gen6bk.com/oauth2/auth
spec:
  tls:
  - secretName: tekton-dashboard-tls
    hosts:
    - tekton.qa.us-east-1.dev.gen6bk.com
  rules:
  - host: tekton.qa.us-east-1.dev.gen6bk.com
    http:
      paths:
      - backend:
          serviceName: tekton-dashboard
          servicePort: 9097
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: infra-cd-webhook-run
  namespace: tekton-pipelines
spec:
  taskRef:
    name: create-webhook
  params:
  - name: GitHubOrg
    value: "gen6-ventures"
  - name: GitHubUser
    value: "gen6ci"
  - name: GitHubRepo
    value: "infra"
  - name: GitHubSecretName
    value: git-webhook
  - name: ExternalDomain
    value: infra-cd.qa.us-east-1.dev.gen6bk.com 
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: infra-cd
  namespace: tekton-pipelines
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx-external
spec:
  tls:
  - hosts:
    - infra-cd.qa.us-east-1.dev.gen6bk.com
    secretName: infra-cd-tls
  rules:
  - host: infra-cd.qa.us-east-1.dev.gen6bk.com
    http:
      paths:
      - path: /
        backend:
          serviceName: el-infra-cd
          servicePort: 8080
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: infra-cd
  namespace: tekton-pipelines
spec:
  params:
  - name: kustomizeDir
    description: The path to the kustomize dir we're applying, relative to repo root
    default: k8s/qa
  - name: git-url
    description: The path to the Github repository we should apply
    default: https://github.com/gen6-ventures/infra.git
  - name: git-revision
    description: The revision or tag to apply
    default: master
  workspaces:
    - name: git-source
  tasks:
  - name: fetch-from-git
    taskRef:
      name: git-clone
    params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.git-revision)
    workspaces:
      - name: output
        workspace: git-source
  - name: apply-k8s
    runAfter: [fetch-from-git]
    taskRef:
      name: kustomize-apply
      kind: ClusterTask
    params:
    - name: git-revision
      value: "$(tasks.fetch-from-git.results.commit)"
    - name: kustomizeDir
      value: "$(params.kustomizeDir)"
    workspaces:
      - name: source
        workspace: git-source
  - name: test-k8s
    runAfter: [apply-k8s]
    taskRef:
      name: k8s-test
      kind: ClusterTask
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kops-cd
  namespace: tekton-pipelines
spec:
  params:
  - name: kopsFile
    description: The path to the kops file we're applying, relative to repo root
    default: k8s/qa.yaml
  - name: git-url
    description: The path to the Github repository we should apply
    default: https://github.com/gen6-ventures/infra.git
  - name: git-revision
    description: The revision or tag to apply
    default: master
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: terraform-cd
  namespace: tekton-pipelines
spec:
  params:
  - name: terraformDir
    description: The path to the terraform dir we're applying, relative to repo root
    default: terraform/dev
  - name: git-url
    description: The path to the Github repository we should apply
    default: https://github.com/11fsconsulting/infra.git
  - name: git-revision
    description: The revision or tag to apply
    default: master
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: infra-cd
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: infra-cd
    interceptors:
    - github:
        eventTypes:
        - push
        secretRef:
          secretKey: secret-string
          secretName: git-webhook
    - cel:
        filter: |-
          (header.match('X-GitHub-Event', 'push') &&
           body.repository.name == 'infra') &&
           body.ref.startsWith('refs/heads/master')
    name: kops-cd
    template:
      name: kops-cd
  - bindings:
    - kind: TriggerBinding
      ref: infra-cd
    interceptors:
    - github:
        eventTypes:
        - push
        secretRef:
          secretKey: secret-string
          secretName: git-webhook
    - cel:
        filter: |-
          (header.match('X-GitHub-Event', 'push') &&
           body.repository.name == 'infra') &&
           body.ref.startsWith('refs/heads/master')
    name: infra-cd
    template:
      name: infra-cd
