---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: mino-cards
  annotations:
    secret.reloader.stakater.com/reload: "mino-cards-marqeta-password,mino-cards-db-password"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mino-cards
  template:
    spec:
      containers:
        - name: mino-cards
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mino-cards-db-password
                  key: password
            - name: POSTGRES_USER
              value: cards
              valueFrom: null
