apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - disruptionbudget.yaml
  - service.yaml
  - service-monitor.yaml

configMapGenerator:
  - name: mino-disclosures-env-vars
    literals:
      - SWAGGER_ENABLED=false
      - SENTRY_DSN=https://d91a477b8fd5413bb764dac8371de6f0@sentry.io/5175033
