---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-onboarding-itunes-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - onboarding-itunes-staging
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-onboarding-client-credentials-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - onboarding-client-credentials-staging
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-onboarding-intercom-token
secretDescriptor:
  backendType: secretsManager
  data:
    - key: intercom-token-staging
      name: token
