---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-identity-intercom-token
secretDescriptor:
  backendType: secretsManager
  data:
    - key: intercom-token-prod
      name: token
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-identity-client-credentials-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - identity-client-credentials-prod
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-db-identity-user
secretDescriptor:
  backendType: secretsManager
  data:
    - key: identity-db-password-prod
      name: PASSWORD
