---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-registrations-apns-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - apns-signing-key
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-registrations-jwe-secret-key-v1
secretDescriptor:
  backendType: secretsManager
  data:
    - key: registrations-jwe-secret-key-int-v1
      name: jwe-secret-key
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-registrations-client-credentials-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - registration-client-credentials-int
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-registrations-iv-secret-key
secretDescriptor:
  backendType: secretsManager
  data:
    - key: registrations-iv-secret-key-int
      name: iv-secret-key
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-registrations-apns-cert
secretDescriptor:
  backendType: secretsManager
  data:
    - key: registrations-apns-cert-int
      property: crt
      name: crt
    - key: registrations-apns-cert-int
      property: key
      name: key
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-registrations-apns-cert-dev
secretDescriptor:
  backendType: secretsManager
  data:
    - key: registrations-apns-cert-int-dev
      property: crt
      name: crt
    - key: registrations-apns-cert-int-dev
      property: key
      name: key
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-registrations-fcm-service-account
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - registrations-fcm-service-account-int
