---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-transactions-mx-api-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - mx-api-staging
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-transactions-marqeta-password
secretDescriptor:
  backendType: secretsManager
  data:
    - key: marqeta-password-staging
      name: password
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-transactions-client-credentials-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - transactions-client-credentials-staging
