apiVersion: v1
kind: Service
metadata:
  name: mino-webhooks
  labels:
    app: mino-webhooks
spec:
  ports:
    - port: 8443
      name: https
    - port: 8081
      name: http-actuator
  selector:
    app: mino-webhooks
  type: ClusterIP
