{
 "title": "Top-ups over time",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account",
    "label": "Account ID",
    "query": "SELECT id FROM reporting.spending_account ORDER BY 1"
   }
  ]
 },
 "panels": [
  { "title": "Engagement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average time to first top-up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Hours" }
   ],
   "targets": [
    {
     "rawSql": "select * from reporting.first_top_up_by_month;"
    }
   ]
  },
  {
   "title": "Top-up amount over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "USD" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date_trunc('month', time) as time, sum(sum_top_up_amount)\nfrom reporting.top_up_amount_by_month\nwhere (account_id = '${account:raw}' OR '${account:raw}' = 'All accounts')\ngroup by date_trunc('month', time)\norder by 1;"
    }
   ]
  },
  { "title": "Amounts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Average top-up amount over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "USD" }
   ],
   "targets": [
    {
     "rawSql": "\nSELECT date_trunc('month', time) as time, sum(avg_top_up_amount) as average\nfrom reporting.average_top_up_amount_by_month\nwhere (account_id = '${account:raw}' OR '${account:raw}' = 'All accounts')\ngroup by date_trunc('month', time)\norder by 1;"
    }
   ]
  },
  {
   "title": "Number of top-ups",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "USD" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date_trunc('month', time) as \"time\", count(1) as top_ups\nfrom reporting.top_up_count_by_month\nwhere (account_id = '${account:raw}' OR '${account:raw}' = 'All accounts')\ngroup by date_trunc('month', time)\norder by 1"
    }
   ]
  }
 ]
}
{
 "title": "Top-up insights",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Behaviour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User cohorts by count of top-ups",
   "type": "bargauge",
   "description": "percentage of users with 1 top vs more than 1 top up vs 0 top ups",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from reporting.top_up_cohorts;"
    }
   ]
  },
  { "title": "Engagement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Average time between top ups",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from reporting.avg_time_between_top_ups; "
    }
   ]
  },
  {
   "title": "Average time between to first top up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from reporting.avg_time_to_first_top_up;"
    }
   ]
  },
  { "title": "Amounts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Average amount of top-up",
   "type": "stat",
   "description": "Average amount of top-up across all users",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from reporting.avg_top_up_amount;"
    }
   ]
  },
  {
   "title": "All top-up",
   "type": "stat",
   "description": "Sum of all top-ups",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from reporting.sum_all_top_up_amount;"
    }
   ]
  },
  {
   "title": "Top 5 accounts by top-ups",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select * from reporting.top_5_accounts_by_top_up_amount;"
    }
   ]
  },
  {
   "title": "Top 5 accounts by top-ups",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 15 },
   "targets": [
    {
     "rawSql": "select * from reporting.top_5_accounts_by_top_up_count;"
    }
   ]
  }
 ]
}
{
 "title": "Customer Metric Dashboard",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  { "title": "User Numbers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Number of Customers",
   "type": "graph",
   "description": "The number of customers who have completed onboarding (not necessarily activated their card yet)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time,total_live_customers as \"total live customers\" from reporting.total_cumulative_live_customers_by_month;"
    },
    {
     "rawSql": "select * from reporting.total_cumulative_users_by_month;"
    }
   ]
  },
  {
   "title": "Number of Customer Conversions By Month",
   "type": "graph",
   "description": "Number of customers that make it through each stage in the funnel. Onboarded customers are counted as customers who have completed the onboarding process, not necessarily activated their card. Sign ups are counted as customers who have started the onboarding process by signing up with the web form.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select * from reporting.customers_month_by_month;"
    },
    {
     "rawSql": "select * from reporting.signups_month_by_month;"
    }
   ]
  },
  {
   "title": "Customer Geography",
   "type": "grafana-worldmap-panel",
   "description": "Location of customers, accurate to the state in which they reside. Customers are counted once they have entered their address during onboarding.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select * from reporting.customer_count_by_state;  "
    }
   ]
  },
  { "title": "Money In & Money Out", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Total Top Amount",
   "type": "stat",
   "description": "The total amount all customers have topped up, over all time, into their milli account.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from reporting.total_top_up_amount_all_time;"
    }
   ]
  },
  {
   "title": "Top-up past 30 days",
   "type": "stat",
   "description": "The total amount that all customers have topped up in the last 30 days.",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from reporting.total_top_up_amount_past_30_days;"
    }
   ]
  },
  {
   "title": "Average Top Up Amount ($)",
   "type": "stat",
   "description": "The mean average of the amount customers transfer into their milli account in a single topup.",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from reporting.average_top_amount;"
    }
   ]
  },
  {
   "title": "Total Spending Value ($) All Time",
   "type": "stat",
   "description": "The total amount that all customers have spent in total, all time.",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from reporting.total_spending_value_all_time;"
    }
   ]
  },
  {
   "title": "Total Spending Value ($) Past 30 Days",
   "type": "stat",
   "description": "The total amount that all customers have spent in the last 30 days.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from reporting.total_spending_value_past_30_days;"
    }
   ]
  },
  {
   "title": "Daily customer topups",
   "type": "graph",
   "description": "The amount of customers who have made at least one topup on each day",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Customers" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  user_count\nFROM\n  reporting.daily_customer_topups\nWHERE\n  $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "% Customers that have topped up this month",
   "type": "gauge",
   "description": "Percentage of customers that have made at least one topup during the last 30 days",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  user_percent\nFROM\n  reporting.month_customer_topup_percent\n"
    }
   ]
  },
  {
   "title": "Total $ value in FNBO Savings Accounts",
   "type": "stat",
   "description": "The current total value in $ of all FNBO savings accounts.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM reporting.amount_in_fnbo_accounts;\n"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Transactions Count Per Month",
   "type": "graph",
   "description": "Total count of transactions by month, across all customers, broken down into transaction types.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select * from reporting.spending_transaction_count_by_month;"
    },
    {
     "rawSql": "select * from reporting.savings_deposit_transaction_count_by_month;"
    },
    {
     "rawSql": "select * from reporting.savings_withdrawal_transaction_count_by_month;"
    },
    {
     "rawSql": "select * from reporting.top_up_transaction_count_by_month;"
    }
   ]
  },
  {
   "title": "Transactions Value  ($) Per Month",
   "type": "graph",
   "description": "Total value of transactions in USD by month, across all customers, broken down into transaction types.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select * from reporting.spending_transaction_amount_by_month;"
    },
    {
     "rawSql": "select * from reporting.savings_deposit_transaction_amount_by_month;"
    },
    {
     "rawSql": "select * from reporting.savings_withdrawal_transaction_amount_by_month;"
    },
    {
     "rawSql": "select * from reporting.top_up_transaction_amount_by_month;"
    }
   ]
  },
  {
   "title": "Total Spending Transactions Count All Time",
   "type": "stat",
   "description": "Total count of all spending transactions from all customers over all time",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from reporting.total_spending_transactions_count_all_time;"
    }
   ]
  },
  {
   "title": "Total Spending Transactions Last 30 Days",
   "type": "stat",
   "description": "Total count of spending transactions in the last 30 days from all customers",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from reporting.total_spending_transactions_count_last_30_days;"
    }
   ]
  },
  { "title": "Feature Uptake", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "% Customers with Savings Jar",
   "type": "gauge",
   "description": "Percentage of customers who have an active savings jar",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from reporting.savings_feature_uptake_percentage;"
    }
   ]
  },
  {
   "title": "% Customers with Spending Challenge",
   "type": "gauge",
   "description": "Percentage of customers who have an active spending challenge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from reporting.spending_challenge_feature_uptake_percentage;"
    }
   ]
  },
  {
   "title": "% Customers with Transaction Roundups",
   "type": "gauge",
   "description": "Percentage of customers who have transaction roundups active",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select * from reporting.savings_rule_transaction_roundup_uptake_percentage;"
    }
   ]
  },
  {
   "title": "% Customers with FNBO Savings Account",
   "type": "gauge",
   "description": "The amount of customers who have created at least one FNBO savings account in Milli",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select * from reporting.percent_customers_with_fnbo_savings_accounts;"
    }
   ]
  }
 ]
}