apiVersion: v1
kind: Service
metadata:
  labels:
    app: cp-schema-registry
    chart: cp-schema-registry-0.1.0
    heritage: Helm
    release: platform
  name: platform-cp-schema-registry
  namespace: kafka
spec:
  ports:
  - name: schema-registry
    port: 8081
  - name: prometheus
    port: 5556
  selector:
    app: cp-schema-registry
    release: platform
