apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-api-gateway-twilio-api-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - twillio-api-dev
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mino-api-gateway-client-credentials-secret
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - api-gateway-client-credentials-int
