---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: mino-onboarding
  labels:
    app: mino-onboarding
    db: "mino"
    auth: "okta"
  annotations:
    configmap.reloader.stakater.com/reload: "mino-onboarding-env-vars"
    secret.reloader.stakater.com/reload: "milli-server-tls,rds-cert,mino-db-onboarding-user,mino-onboarding-itunes-secret,mino-onboarding-intercom-token,mino-onboarding-client-credentials-secret"
spec:
  progressDeadlineSeconds: 140
  selector:
    matchLabels:
      app: mino-onboarding
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mino-onboarding
        db: "mino"
        auth: "okta"
    spec:
      containers:
        - image: 850315125037.dkr.ecr.us-east-1.amazonaws.com/mino-onboarding:latest
          name: mino-onboarding
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: mino-onboarding-env-vars
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mino-db-onboarding-user
                  key: PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mino-db-onboarding-user
                  key: ROLE
            - name: ITUNES_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mino-onboarding-itunes-secret
                  key: key-id
            - name: ITUNES_KEY_BASE64
              valueFrom:
                secretKeyRef:
                  name: mino-onboarding-itunes-secret
                  key: key-base64
            - name: ITUNES_ISSUER
              valueFrom:
                secretKeyRef:
                  name: mino-onboarding-itunes-secret
                  key: issuer
            - name: INTERCOM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mino-onboarding-intercom-token
                  key: token
            - name: CLIENT_CREDENTIALS_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: mino-onboarding-client-credentials-secret
                  key: domain
            - name: CLIENT_CREDENTIALS_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: mino-onboarding-client-credentials-secret
                  key: client-id
            - name: CLIENT_CREDENTIALS_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mino-onboarding-client-credentials-secret
                  key: client-secret
            - name: CLIENT_CREDENTIALS_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: mino-onboarding-client-credentials-secret
                  key: audience
          ports:
            - containerPort: 8443
              name: https
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 75
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 75
            periodSeconds: 5
          resources:
            requests:
              cpu: "250m"
              memory: "1024Mi"
            limits:
              cpu: "1000m"
              memory: "2048Mi"
