---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: mino-cards
  labels:
    app: mino-cards
    db: "mino"
    auth: "okta"
  annotations:
    configmap.reloader.stakater.com/reload: "mino-cards-env-vars"
    secret.reloader.stakater.com/reload: "milli-server-tls,rds-cert,mino-cards-marqeta-password,mino-db-cards-user"
spec:
  progressDeadlineSeconds: 140
  selector:
    matchLabels:
      app: mino-cards
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mino-cards
        db: "mino"
        auth: "okta"
    spec:
      containers:
        - image: 850315125037.dkr.ecr.us-east-1.amazonaws.com/mino-cards:latest
          name: mino-cards
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: mino-cards-env-vars
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mino-db-cards-user
                  key: ROLE
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mino-db-cards-user
                  key: PASSWORD
            - name: MARQETA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mino-cards-marqeta-password
                  key: password
          ports:
            - containerPort: 8443
              name: https
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 75
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 75
            periodSeconds: 5
          resources:
            requests:
              cpu: "250m"
              memory: "768Mi"
            limits:
              cpu: "1000m"
              memory: "1536Mi"
