apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - disruptionbudget.yaml
  - service.yaml
  - service-monitor.yaml

configMapGenerator:
  - name: mino-audit-env-vars
    literals:
      - SWAGGER_ENABLED=false
      - SENTRY_DSN=https://29cde611b1754b88a6556011fe351d8c@o257648.ingest.sentry.io/5629282
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
