apiVersion: v1
kind: Service
metadata:
  name: mino-audit
  labels:
    app: mino-audit
spec:
  ports:
    - port: 8443
      name: https
    - port: 8081
      name: http-actuator
  selector:
    app: mino-audit
  type: ClusterIP
